#!/bin/bash

echo "🚀 Chat App Deployment Script"
echo "=============================="

echo ""
echo "📋 Prerequisites:"
echo "1. Deploy your backend to Railway/Render/Heroku first"
echo "2. Get your backend URL (e.g., https://your-app.railway.app)"
echo "3. Update the CORS settings in backend/src/index.js with your Vercel domain"
echo ""

echo "🔧 Frontend Deployment Steps:"
echo "1. Go to https://vercel.com"
echo "2. Import your GitHub repository"
echo "3. Vercel will automatically detect the frontend configuration"
echo "4. Add environment variable:"
echo "   - Name: VITE_API_URL"
echo "   - Value: https://your-backend-url.railway.app/api"
echo ""

echo "🔧 Backend Deployment Steps:"
echo "1. Deploy to Railway (recommended):"
echo "   - Go to https://railway.app"
echo "   - Create new project"
echo "   - Connect GitHub repo"
echo "   - Set root directory to 'backend'"
echo "   - Add environment variables:"
echo "     * MONGODB_URI"
echo "     * JWT_SECRET"
echo "     * CLOUDINARY_CLOUD_NAME"
echo "     * CLOUDINARY_API_KEY"
echo "     * CLOUDINARY_API_SECRET"
echo "     * NODE_ENV=production"
echo ""

echo "⚠️  Important Notes:"
echo "- Update CORS origins in backend/src/index.js with your Vercel domain"
echo "- Make sure your MongoDB database is accessible"
echo "- Test WebSocket connections after deployment"
echo ""

echo "✅ Ready to deploy!" 